sudo: required
services:
  - docker

before_install:
  - docker build -t pereter/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true pereter/react-test npm test -- --coverage

after_success:
 - docker build -t pereter/multi-client ./client
 - docker build -t pereter/multi-server ./server
 - docker build -t pereter/multi-nginx ./nginx
 - docker build -t pereter/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push pereter/multi-client
 - docker push pereter/multi-server
 - docker push pereter/multi-nginx
 - docker push pereter/multi-worker
